'use client';

import { useEffect, useCallback, useRef, useState } from 'react';
import { escapeHtml as esc } from '@/lib/utils';
import styles from '@/styles/favicongen.module.css';

type PreviewImage = {
  dataUrl: string;
  name: string;
  width: number;
  height: number;
};

const defaultValues = {
  siteName: 'My Awesome Site',
  siteUrl: 'https://example.com',
  siteDesc: 'A polished website with a modern browser experience.',
  themeColor: '#1a1a1a',
  ogType: 'website',
  htmlLang: 'en',
  keywords: 'portfolio, design, creative studio',
};

const previewSizes = [
  { id: 'prev16', size: 16 },
  { id: 'prev32', size: 32 },
  { id: 'prev64', size: 64 },
  { id: 'prev180', size: 60 },
  { id: 'prev192', size: 48 },
];

export default function FaviconGenerator() {
  const [image, setImage] = useState<PreviewImage | null>(null);
  const [form, setForm] = useState(defaultValues);
  const [output, setOutput] = useState('');
  const [generated, setGenerated] = useState(false);
  const [copied, setCopied] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  const handleFile = (file?: File | null) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        const dataUrl = imgToDataUrl(img, 512);
        setImage({ dataUrl, name: file.name, width: img.width, height: img.height });
        setGenerated(false);
        setOutput('');
      };
      img.src = reader.result as string;
    };
    reader.readAsDataURL(file);
  };

  const renderPreviews = useCallback((img: HTMLImageElement) => {
    previewSizes.forEach(({ id, size }) => {
      const element = document.getElementById(id) as HTMLCanvasElement | null;
      if (!element) return;
      const ctx = element.getContext('2d');
      if (!ctx) return;
      ctx.clearRect(0, 0, size, size);
      ctx.drawImage(img, 0, 0, size, size);
    });
  }, []);

  useEffect(() => {
    if (!image) return;
    const img = new Image();
    img.onload = () => renderPreviews(img);
    img.src = image.dataUrl;
  }, [image, renderPreviews]);

  const clearImage = () => {
    setImage(null);
    setGenerated(false);
    setOutput('');
    if (fileRef.current) {
      fileRef.current.value = '';
    }
  };

  const imgToDataUrl = (img: HTMLImageElement, size: number) => {
    const canvas = canvasRef.current;
    if (!canvas) return '';
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';
    ctx.clearRect(0, 0, size, size);
    ctx.drawImage(img, 0, 0, size, size);
    return canvas.toDataURL('image/png');
  };

  const generateAll = () => {
    const name = form.siteName.trim() || 'My Site';
    const url = (form.siteUrl.trim() || 'https://example.com').replace(/\/$/, '');
    const desc = form.siteDesc.trim() || '';
    const theme = form.themeColor || '#1a1a1a';
    const ogType = form.ogType;
    const lang = form.htmlLang;
    const kw = form.keywords.trim();

    const f16 = image ? imgToDataUrl(new Image(), 16) : '';
    const f32 = image ? imgToDataUrl(new Image(), 32) : '';
    const f180 = image ? imgToDataUrl(new Image(), 180) : '';
    const f192 = image ? imgToDataUrl(new Image(), 192) : '';
    const f512 = image ? imgToDataUrl(new Image(), 512) : '';

    const faviconLines = image
      ? `
  <!-- Favicons -->
  <link rel="icon" type="image/png" sizes="16x16" href="${f16}">
  <link rel="icon" type="image/png" sizes="32x32" href="${f32}">
  <link rel="apple-touch-icon" sizes="180x180" href="${f180}">
  <link rel="icon" type="image/png" sizes="192x192" href="${f192}">
  <link rel="icon" type="image/png" sizes="512x512" href="${f512}">
  <link rel="shortcut icon" href="${f32}">`
      : `
  <!-- Favicons (add your favicon files) -->
  <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png">
  <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="favicons/android-chrome-192x192.png">
  <link rel="icon" type="image/png" sizes="512x512" href="favicons/android-chrome-512x512.png">
  <link rel="shortcut icon" href="favicons/favicon.ico">`;

    const ogImage = image ? f512 : `${url}/og-image.png`;
    const code = `<!-- ═══════════════════════════════════════════ -->
<!-- Generated by Favicon & Meta Generator      -->
<!-- ═══════════════════════════════════════════ -->

<!-- Charset & Viewport -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Primary Meta Tags -->
<title>${name}</title>
<meta name="title" content="${name}">
${desc ? `<meta name="description" content="${esc(desc)}">` : ''}
${kw ? `<meta name="keywords" content="${esc(kw)}">` : ''}
<meta name="author" content="${name}">
<meta name="robots" content="index, follow">
<meta name="language" content="${lang}">
<meta name="theme-color" content="${theme}">
<link rel="canonical" href="${url}/">
${faviconLines}

  <!-- Web Manifest -->
  <link rel="manifest" href="site.webmanifest">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="${ogType}">
<meta property="og:url" content="${url}/">
<meta property="og:title" content="${name}">
${desc ? `<meta property="og:description" content="${esc(desc)}">` : ''}
<meta property="og:image" content="${ogImage}">
<meta property="og:image:width" content="512">
<meta property="og:image:height" content="512">
<meta property="og:site_name" content="${name}">
<meta property="og:locale" content="${lang}_${lang.toUpperCase()}">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="${url}/">
<meta name="twitter:title" content="${name}">
${desc ? `<meta name="twitter:description" content="${esc(desc)}">` : ''}
<meta name="twitter:image" content="${ogImage}">

<!-- Schema.org / Structured Data -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "${name}",
  "url": "${url}/",
  "description": "${esc(desc || name)}"
}
<\/script>

<!-- PWA / Mobile -->
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="${name}">
<meta name="msapplication-TileColor" content="${theme}">
<meta name="msapplication-config" content="browserconfig.xml">`;

    setOutput(code);
    setGenerated(true);
  };

  const copyCode = async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };

  const downloadAssets = () => {
    if (!image) {
      window.alert('Upload an image first to download favicon files.');
      return;
    }

    const sizes = [
      [16, 'favicon-16x16'],
      [32, 'favicon-32x32'],
      [180, 'apple-touch-icon'],
      [192, 'android-chrome-192x192'],
      [512, 'android-chrome-512x512'],
    ] as const;

    sizes.forEach(([size, name]) => {
      const link = document.createElement('a');
      link.href = imgToDataUrl(new Image(), size);
      link.download = `${name}.png`;
      link.click();
    });

    const manifest = JSON.stringify(
      {
        name: form.siteName || 'My Site',
        short_name: (form.siteName || 'Site').split(' ')[0],
        icons: [
          { src: '/favicons/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: '/favicons/android-chrome-512x512.png', sizes: '512x512', type: 'image/png' },
        ],
        theme_color: form.themeColor,
        background_color: '#ffffff',
        display: 'standalone',
      },
      null,
      2
    );

    const blob = new Blob([manifest], { type: 'application/json' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'site.webmanifest';
    link.click();
  };

  return (
    <div className="tool-panel">
      <div className="tool-grid">
        <section className="tool-form card">
          <div className="section-header">
            <h2>Image &amp; site details</h2>
            <p>Upload a logo and fill in the metadata you want to publish.</p>
          </div>

          <div
            className={`${styles.dropZone} ${dragActive ? styles.isActive : ''}`}
            onDragOver={(event) => {
              event.preventDefault();
              setDragActive(true);
            }}
            onDragLeave={() => setDragActive(false)}
            onDrop={(event) => {
              event.preventDefault();
              setDragActive(false);
              handleFile(event.dataTransfer.files?.[0]);
            }}
            onClick={() => fileRef.current?.click()}
          >
            {image ? (
              <div className={styles.dropZonePreview}>
                <div className={styles.previewRow}>
                  <div className={styles.previewSizes}>
                    {previewSizes.map(({ id, size }) => (
                      <div key={id} className={styles.previewItem}>
                        <canvas id={id} width={size} height={size} />
                        <span>{size}</span>
                      </div>
                    ))}
                  </div>
                  <div className={styles.previewMeta}>
                    <p className={styles.previewName}>{image.name}</p>
                    <p className={styles.previewDims}>{image.width} × {image.height}px</p>
                    <button type="button" className={styles.btnGhost} onClick={(event) => {
                      event.stopPropagation();
                      clearImage();
                    }}>
                      Change image
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              <div className={styles.dropZoneEmpty}>
                <p>Drop your logo or icon here</p>
                <p>PNG, SVG, JPG. Square image works best.</p>
              </div>
            )}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              hidden
              onChange={(event) => handleFile(event.target.files?.[0])}
            />
          </div>

          <div className="field-group">
            <label>Site name</label>
            <input
              value={form.siteName}
              onChange={(event) => setForm((prev) => ({ ...prev, siteName: event.target.value }))}
              placeholder="My Awesome Site"
            />
          </div>

          <div className="field-group">
            <label>Site URL</label>
            <input
              value={form.siteUrl}
              onChange={(event) => setForm((prev) => ({ ...prev, siteUrl: event.target.value }))}
              placeholder="https://example.com"
            />
          </div>

          <div className="field-group">
            <label>Short description</label>
            <textarea
              rows={3}
              value={form.siteDesc}
              onChange={(event) => setForm((prev) => ({ ...prev, siteDesc: event.target.value }))}
              placeholder="What does your website do?"
            />
          </div>

          <div className="field-group color-fields">
            <div>
              <label>Theme color</label>
              <div className={styles.colorRow}>
                <input
                  type="color"
                  value={form.themeColor}
                  onChange={(event) => setForm((prev) => ({ ...prev, themeColor: event.target.value }))}
                />
                <input
                  value={form.themeColor}
                  onChange={(event) => setForm((prev) => ({ ...prev, themeColor: event.target.value }))}
                  placeholder="#1a1a1a"
                />
              </div>
            </div>
            <div>
              <label>Content type</label>
              <select
                value={form.ogType}
                onChange={(event) => setForm((prev) => ({ ...prev, ogType: event.target.value }))}
              >
                <option value="website">website</option>
                <option value="article">article</option>
                <option value="product">product</option>
                <option value="profile">profile</option>
              </select>
            </div>
            <div>
              <label>Language</label>
              <select
                value={form.htmlLang}
                onChange={(event) => setForm((prev) => ({ ...prev, htmlLang: event.target.value }))}
              >
                <option value="en">English (en)</option>
                <option value="tr">Turkish (tr)</option>
                <option value="de">German (de)</option>
                <option value="fr">French (fr)</option>
                <option value="es">Spanish (es)</option>
                <option value="pt">Portuguese (pt)</option>
                <option value="ja">Japanese (ja)</option>
                <option value="zh">Chinese (zh)</option>
                <option value="ar">Arabic (ar)</option>
              </select>
            </div>
          </div>

          <div className="field-group">
            <label>Keywords</label>
            <input
              value={form.keywords}
              onChange={(event) => setForm((prev) => ({ ...prev, keywords: event.target.value }))}
              placeholder="portfolio, design, creative studio"
            />
          </div>

          <button type="button" className="btn-primary" onClick={generateAll}>
            Generate head code →
          </button>
        </section>

        <section className="tool-preview card">
          <div className="section-header">
            <h2>Generated head code</h2>
            <p>Copy and paste the result into your site’s head section.</p>
          </div>

          {!generated ? (
            <div className="helper-text">Generate the snippet to preview your output.</div>
          ) : (
            <>
              <div className={styles.badgeRow}>
                <span className={`${styles.badge} ${styles.badgeSuccess}`}>Primary meta</span>
                <span className={`${styles.badge} ${styles.badgeSuccess}`}>Open Graph</span>
                <span className={`${styles.badge} ${styles.badgeSuccess}`}>Twitter Card</span>
                <span className={`${styles.badge} ${styles.badgeInfo}`}>Schema.org</span>
                <span className={`${styles.badge} ${styles.badgeInfo}`}>PWA tags</span>
              </div>
              <pre className={styles.outputCode}>{output}</pre>
              <div className={styles.outputActions}>
                <button type="button" className={styles.btnGhost} onClick={copyCode}>
                  {copied ? 'Copied!' : 'Copy code'}
                </button>
                <button type="button" className="btn-primary" onClick={downloadAssets}>
                  Download favicons
                </button>
              </div>
            </>
          )}
        </section>
      </div>
      <canvas ref={canvasRef} className={styles.hiddenCanvas} />
    </div>
  );
}
